[package]
name = "tools"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
schemars = "1.2.1"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
telemetry = { path = "../telemetry" }
thiserror = "2.0.18"
tracing.workspace = true
uuid = { version = "1.23.1", features = ["v7"] }

[dev-dependencies]
serde_yaml.workspace = true
