[package]
name = "domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
derive = { path = "../derive" }
rand = "0.10.1"
serde = { workspace = true, features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }
taskstore-traits = { workspace = true }

[dev-dependencies]
serde_json.workspace = true
taskstore-traits.workspace = true
