[package]
name = "llm"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
domain = { path = "../domain" }
reqwest = { version = "0.13.2", default-features = false, features = ["json", "rustls", "http2"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
telemetry = { path = "../telemetry" }
thiserror = "2.0.18"

[dev-dependencies]
serde_yaml.workspace = true
tokio = { version = "1.52.1", features = ["macros", "rt"] }
wiremock = "0.6.5"
